### ISSUE TITLE
Migration to more recent MPS version and namespace issue

### ISSUE THREAD

**Issue by fvollmer** [maystar/LanguageVisualization#2]
Hi,
thanks for your nice project. I just decided to migrate it to MPS 2018.3 (will migrate it to 2019.1 soon). Further I made some more changes:
 * Remove sandbox project due to a dependency to modHDL. This way the project only depends on MPS and mbeddr platform
 * Remove generated code from repository and add `.gitignore`
 * Add gradle build script for easier builds

I'll provide a pull request if you are happy with these changes. You can find my fork here: https://github.com/fvollmer/LanguageVisualization.

I noticed you are using the `jetbrains.mps.*` namespace. As far as I can see this language isn't an official language by jetbrains. What do you think about changing the namespace to avoid confusion?

**Comment by maystar** [comment]
Hey @fvollmer,
I'm happy that these old piece of code is useful to someone! Please feel free to modify the code in your fork as you want. If you like, I can add link to this fork in the readme. I haven't used MPS for several years, I doubt that I'll touch this code again.

**Comment by fvollmer** [comment]
Ok, then I'll just maintain it as my own fork, but I'm not sure how much time I'll have to maintain it.
